In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as  plt

In [3]:
dataset=pd.read_csv('/home/shridhar/Documents/Tensorflow learning/Tensorflow-Bootcamp-master/02-TensorFlow-Basics/pima-indians-diabetes.csv')

In [17]:
X=dataset.iloc[:,0:7].values
Y=dataset.iloc[:,8].values

In [18]:
from sklearn.model_selection import train_test_split
X_train, x_test, Y_train, y_test = train_test_split(X,Y,test_size=0.3,random_state=0)

In [19]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
x_test=sc.fit_transform(x_test)

In [20]:
X_train

array([[-1.13311543,  0.9144385 ,  1.04559346, ..., -0.71652335,
         1.22646853, -0.3002719 ],
       [-0.8391623 , -1.19655127, -0.08570438, ..., -0.71652335,
        -1.75097771,  0.45699051],
       [-0.54520916,  0.01416345,  0.01714088, ..., -0.71652335,
         0.56619802, -0.39305899],
       ...,
       [ 0.0426971 , -0.85506763, -0.23997227, ..., -0.71652335,
        -0.941212  , -0.96774035],
       [ 2.10036903, -1.13446334,  0.22283139, ..., -0.71652335,
        -0.26848356, -0.51278428],
       [ 0.33665024,  0.44877899,  0.63421243, ..., -0.71652335,
        -4.01832171,  0.50488062]])

In [21]:
X

array([[6.        , 0.74371859, 0.59016393, ..., 0.        , 0.50074516,
        0.23441503],
       [1.        , 0.42713568, 0.54098361, ..., 0.        , 0.39642325,
        0.11656704],
       [8.        , 0.91959799, 0.52459016, ..., 0.        , 0.34724292,
        0.25362938],
       ...,
       [5.        , 0.6080402 , 0.59016393, ..., 0.13238771, 0.390462  ,
        0.07130658],
       [1.        , 0.63316583, 0.49180328, ..., 0.        , 0.4485842 ,
        0.11571307],
       [1.        , 0.46733668, 0.57377049, ..., 0.        , 0.45305514,
        0.10119556]])

In [22]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [25]:
#initialize the ANN
classifier=Sequential()

#Adding the input layer and the first hidden layer
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu',input_dim=7))

#Add Second hidden layer
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))

#adding output layer
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

#Compile the ANN
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

#fitting an ANN to the training set
classifier.fit(X_train,Y_train,batch_size=50,epochs=10)

Epoch 1/10
537/537 [==============================] - 1s 1ms/step - loss: 0.6924 - acc: 0.6201
Epoch 2/10
537/537 [==============================] - 0s 33us/step - loss: 0.6908 - acc: 0.6387
Epoch 3/10
537/537 [==============================] - 0s 32us/step - loss: 0.6892 - acc: 0.6387
Epoch 4/10
537/537 [==============================] - 0s 33us/step - loss: 0.6875 - acc: 0.6387
Epoch 5/10
537/537 [==============================] - 0s 34us/step - loss: 0.6851 - acc: 0.6387
Epoch 6/10
537/537 [==============================] - 0s 46us/step - loss: 0.6822 - acc: 0.6387
Epoch 7/10
537/537 [==============================] - 0s 36us/step - loss: 0.6784 - acc: 0.6387
Epoch 8/10
537/537 [==============================] - 0s 31us/step - loss: 0.6733 - acc: 0.6387
Epoch 9/10
537/537 [==============================] - 0s 36us/step - loss: 0.6664 - acc: 0.6387
Epoch 10/10
537/537 [==============================] - 0s 40us/step - loss: 0.6580 - acc: 0.6425


In [27]:
y_pred=classifier.predict(x_test)
y_pred=(y_pred>0.5)

In [28]:
#making a confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[154,   3],
       [ 65,   9]])

In [29]:
#Improving the ANN
#Dropout Regularization to reduce overfitting if needed

#tunning the ANN
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense

In [30]:
def build_classifier(optimizer):
    classifier=Sequential()
    classifier.add(Dense(units=6,kernel_initializer='uniform', activation='relu', input_dim=7))
    classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))
    classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))
    classifier.compile(optimizer=optimizer, loss='binary_crossentropy',metrics=['accuracy'])
    return classifier

In [31]:
classifier=KerasClassifier(build_fn=build_classifier)
parameters={'batch_size':[20,25],
           'epochs':[5,10],
           'optimizer':['adam','rmsprop']}

grid_search=GridSearchCV(estimator=classifier,
                        param_grid=parameters,
                        scoring='accuracy',
                        cv=10)
grid_search=grid_search.fit(X_train,Y_train)
best_parameters=grid_search.best_params_
best_accuracy=grid_search.best_score_

Epoch 1/5
483/483 [==============================] - 0s 513us/step - loss: 0.6917 - acc: 0.6211
Epoch 2/5
483/483 [==============================] - 0s 68us/step - loss: 0.6885 - acc: 0.6418
Epoch 3/5
483/483 [==============================] - 0s 69us/step - loss: 0.6846 - acc: 0.6418
Epoch 4/5
483/483 [==============================] - 0s 75us/step - loss: 0.6776 - acc: 0.6418
Epoch 5/5
483/483 [==============================] - 0s 72us/step - loss: 0.6663 - acc: 0.6418
Epoch 1/5
483/483 [==============================] - 0s 569us/step - loss: 0.6916 - acc: 0.6294
Epoch 2/5
483/483 [==============================] - 0s 70us/step - loss: 0.6886 - acc: 0.6335
Epoch 3/5
483/483 [==============================] - 0s 73us/step - loss: 0.6844 - acc: 0.6335
Epoch 4/5
483/483 [==============================] - 0s 70us/step - loss: 0.6774 - acc: 0.6335
Epoch 5/5
483/483 [==============================] - 0s 69us/step - loss: 0.6660 - acc: 0.6335
Epoch 1/5
483/483 [=============================

484/484 [==============================] - 0s 78us/step - loss: 0.6884 - acc: 0.6343
Epoch 3/10
484/484 [==============================] - 0s 82us/step - loss: 0.6833 - acc: 0.6343
Epoch 4/10
484/484 [==============================] - 0s 76us/step - loss: 0.6741 - acc: 0.6364
Epoch 5/10
484/484 [==============================] - 0s 82us/step - loss: 0.6590 - acc: 0.6694
Epoch 6/10
484/484 [==============================] - 0s 77us/step - loss: 0.6373 - acc: 0.7500
Epoch 7/10
484/484 [==============================] - 0s 74us/step - loss: 0.6102 - acc: 0.7686
Epoch 8/10
484/484 [==============================] - 0s 74us/step - loss: 0.5812 - acc: 0.7851
Epoch 9/10
484/484 [==============================] - 0s 76us/step - loss: 0.5520 - acc: 0.7831
Epoch 10/10
484/484 [==============================] - 0s 72us/step - loss: 0.5286 - acc: 0.7872
Epoch 1/10
484/484 [==============================] - 1s 2ms/step - loss: 0.6918 - acc: 0.6343
Epoch 2/10
484/484 [==============================]

484/484 [==============================] - 0s 89us/step - loss: 0.6891 - acc: 0.6343
Epoch 3/5
484/484 [==============================] - 0s 120us/step - loss: 0.6858 - acc: 0.6343
Epoch 4/5
484/484 [==============================] - 0s 82us/step - loss: 0.6810 - acc: 0.6343
Epoch 5/5
484/484 [==============================] - 0s 91us/step - loss: 0.6730 - acc: 0.6343
Epoch 1/5
484/484 [==============================] - 2s 3ms/step - loss: 0.6918 - acc: 0.6240
Epoch 2/5
484/484 [==============================] - 0s 85us/step - loss: 0.6888 - acc: 0.6364
Epoch 3/5
484/484 [==============================] - 0s 96us/step - loss: 0.6839 - acc: 0.6364
Epoch 4/5
484/484 [==============================] - 0s 153us/step - loss: 0.6757 - acc: 0.6364
Epoch 5/5
484/484 [==============================] - 0s 128us/step - loss: 0.6621 - acc: 0.6364
Epoch 1/5
483/483 [==============================] - 2s 3ms/step - loss: 0.6913 - acc: 0.6294
Epoch 2/5
483/483 [==============================] - 0s 95u

483/483 [==============================] - 0s 109us/step - loss: 0.5970 - acc: 0.6439
Epoch 9/10
483/483 [==============================] - 0s 95us/step - loss: 0.5738 - acc: 0.6460
Epoch 10/10
483/483 [==============================] - 0s 92us/step - loss: 0.5576 - acc: 0.6522
Epoch 1/10
483/483 [==============================] - 2s 4ms/step - loss: 0.6917 - acc: 0.6377
Epoch 2/10
483/483 [==============================] - 0s 93us/step - loss: 0.6889 - acc: 0.6460
Epoch 3/10
483/483 [==============================] - 0s 83us/step - loss: 0.6853 - acc: 0.6460
Epoch 4/10
483/483 [==============================] - 0s 96us/step - loss: 0.6803 - acc: 0.6460
Epoch 5/10
483/483 [==============================] - 0s 89us/step - loss: 0.6729 - acc: 0.6460
Epoch 6/10
483/483 [==============================] - 0s 84us/step - loss: 0.6614 - acc: 0.6460
Epoch 7/10
483/483 [==============================] - 0s 93us/step - loss: 0.6463 - acc: 0.6501
Epoch 8/10
483/483 [==============================

483/483 [==============================] - 0s 98us/step - loss: 0.6845 - acc: 0.6377
Epoch 4/10
483/483 [==============================] - 0s 107us/step - loss: 0.6810 - acc: 0.6625
Epoch 5/10
483/483 [==============================] - 0s 99us/step - loss: 0.6767 - acc: 0.6977
Epoch 6/10
483/483 [==============================] - 0s 102us/step - loss: 0.6710 - acc: 0.7350
Epoch 7/10
483/483 [==============================] - 0s 99us/step - loss: 0.6653 - acc: 0.7536
Epoch 8/10
483/483 [==============================] - 0s 101us/step - loss: 0.6589 - acc: 0.7640
Epoch 9/10
483/483 [==============================] - 0s 90us/step - loss: 0.6520 - acc: 0.7640
Epoch 10/10
483/483 [==============================] - 0s 97us/step - loss: 0.6449 - acc: 0.7640
Epoch 1/10
483/483 [==============================] - 2s 4ms/step - loss: 0.6915 - acc: 0.6190
Epoch 2/10
483/483 [==============================] - 0s 93us/step - loss: 0.6887 - acc: 0.6439
Epoch 3/10
483/483 [============================

In [32]:
best_parameters

{'batch_size': 20, 'epochs': 10, 'optimizer': 'adam'}

In [33]:
best_accuracy

0.7392923649906891

In [ ]:
###Create model
# Input - Layer

model.add(layers.Dense(50, activation = "relu", input_shape=(10000, )))
# Hidden - Layers
model.add(layers.Dropout(0.3, noise_shape=None, seed=None))
model.add(layers.Dense(50, activation = "relu"))
model.add(layers.Dropout(0.2, noise_shape=None, seed=None))
model.add(layers.Dense(50, activation = "relu"))
# Output- Layer
model.add(layers.Dense(1, activation = "sigmoid"))model.summary()
model.summary()
          
model.compile(optimizer = "adam",loss = "binary_crossentropy", metrics = ["accuracy"])


results = model.fit(
 train_x, train_y,
 epochs= 2,
 batch_size = 500,
 validation_data = (test_x, test_y)
)


In [ ]:
https://towardsdatascience.com/how-to-build-a-neural-network-with-keras-e8faa33d0ae4